version: "3.3"

services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - "./test.env"
    restart: always

  redis:
    container_name: redis
    image: "redis:alpine"
    volumes:
      - ./storage/redis/data:/data
    restart: always

  tgbot:
    container_name: tgbot
    image: docker.pkg.github.com/pip-install-hse/destreambot/tg_bot:latest
    working_dir: "/code"
    depends_on:
      - db
    env_file:
      - "./test.env"
    command: sh -c "python start_tg_bot.py"
    restart: always

  celery:
    container_name: celery
    image: docker.pkg.github.com/pip-install-hse/destreambot/tg_bot:latest
    working_dir: "/code/tg_bot"
    command: celery -A adminka worker -l info
    env_file:
      - "./test.env"
    depends_on:
      - redis

  celery-beat:
    container_name: celery-beat
    image: docker.pkg.github.com/pip-install-hse/destreambot/tg_bot:latest
    working_dir: "/code/tg_bot"
    command: sh -c "rm -rf celerybeat.pid && celery -A adminka beat -l info"
    env_file:
      - "./test.env"
    depends_on:
      - redis
